import Head from "next/head";
import Navbar from "components/navbar";
import styles from "styles/Home.module.css";

export default function Layout({ children }) {
  return (
    <div className={styles.bgimage}>
      <Head>
        <title>X-lab</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>{children}</main>
      <foot>this is footer</foot>
    </div>
  );
}
