import { Box } from "@chakra-ui/react";
import Head from "next/head";
import Navbar from "../components/NavBar";
import styles from "../styles/Home.module.css";
import Footer from "./Footer";

export default function Layout({ children }) {
  return (
    <div className={styles.bgimage}>
      <Head>
        <title>X-lab</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>
        <Box paddingTop="100px" minH="100vh">
          {children}
        </Box>
      </main>
      <Footer /> 
    </div>
  );
}
